default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: 5432

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'product_dev') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'product_test') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'product_production') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'product_prod') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'product_prod') %>
